# -*- coding: utf-8 -*-
"""FINAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fpym-WI_jkD2haPkmKPy5FH4dUxUKiCv
"""

import math
import random

# Parámetros globales
F = 0.5                  # Constante para latencia de recuperación
THETA = 0.7              # Aleatoriedad en elección de producción
UMBRAL_RECUPERACION = 1.5  # Umbral mínimo para recuperar un chunk

# Clase CHUNK (unidad de conocimiento)
class Chunk:
    def __init__(self, concepto, definicion, analogia=None, fuente_externa=None):
        self.concepto = concepto                      # Nombre del concepto
        self.definicion = definicion                  # Definición formal
        self.analogia = analogia                      # Analogía usada para explicar
        self.fuente_externa = fuente_externa          # Ejemplo o herramienta externa (CSD)
        self.frecuencia = 1                           # Cuántas veces se usa
        self.recencia = 1                             # Tiempo desde el último uso
        self.associaciones = {}                       # Asociación semántica (contexto)
        self.estimulo_externo = 0.0                   # Activación extra por entorno distribuido
        self.ruido = random.gauss(0, 0.1)             # Ruido estocástico (distribución gaussiana)

    # Calcular activación A_i
    def calcular_activacion(self, contexto=None, pesos=None):
        B = math.log(self.frecuencia / self.recencia + 1)  # Activación base
        suma_asociaciones = 0
        if contexto and pesos:
            for j, c in enumerate(contexto):
                fuerza = self.associaciones.get(c, 0.0)
                suma_asociaciones += pesos[j] * fuerza
        A = B + suma_asociaciones + self.estimulo_externo + self.ruido
        self.activacion = A
        return A

    # Calcular tiempo de recuperación
    def tiempo_recuperacion(self):
        return F * math.exp(-self.activacion)

# Clase MEMORIA DECLARATIVA
class MemoriaDeclarativa:
    def __init__(self):
        self.chunks = []

    def agregar(self, chunk):
        self.chunks.append(chunk)

    def buscar(self, termino, contexto=None, pesos=None, externo=False):
        mejor_chunk = None
        max_A = float('-inf')
        for ch in self.chunks:
            if termino.lower() in ch.concepto.lower():
                if externo:
                    ch.estimulo_externo = 0.5  # Activación distribuida
                A = ch.calcular_activacion(contexto, pesos)
                if A > max_A:
                    max_A = A
                    mejor_chunk = ch
        return mejor_chunk if max_A > UMBRAL_RECUPERACION else None

# Función para cargar 5 conceptos ISO 9001:2015
def crear_memoria_iso():
    memoria = MemoriaDeclarativa()

    c1 = Chunk(
        "Enfoque basado en procesos",
        "Gestión de actividades como procesos interrelacionados que contribuyen al valor del cliente.",
        "Como una orquesta: cada instrumento (proceso) aporta a la sinfonía.",
        "Foro ISO, infografía digital, simulación empresarial"
    )
    c1.associaciones = {"orquesta": 0.8, "flujo": 0.6}
    memoria.agregar(c1)

    c2 = Chunk(
        "Mejora continua",
        "Compromiso permanente con la mejora del desempeño global.",
        "Como escalar una montaña paso a paso.",
        "Estudio de caso, retroalimentación grupal"
    )
    c2.associaciones = {"montaña": 0.9, "escalada": 0.6}
    memoria.agregar(c2)

    c3 = Chunk(
        "Enfoque al cliente",
        "Satisfacer y superar las expectativas del cliente es el objetivo central.",
        "Como un restaurante que adapta sus recetas según las opiniones de los comensales.",
        "Encuestas de satisfacción, plataformas de reseñas"
    )
    c3.associaciones = {"cliente": 0.9, "satisfacción": 0.7}
    memoria.agregar(c3)

    c4 = Chunk(
        "Liderazgo",
        "Los líderes establecen dirección y fomentan una cultura de compromiso.",
        "Como el capitán de un barco que guía el rumbo de su tripulación.",
        "Simuladores de liderazgo, entrevistas con directivos"
    )
    c4.associaciones = {"capitán": 0.85, "dirección": 0.6}
    memoria.agregar(c4)

    c5 = Chunk(
        "Toma de decisiones basada en la evidencia",
        "Las decisiones eficaces se fundamentan en el análisis de datos y hechos.",
        "Como un médico que receta basado en exámenes clínicos, no suposiciones.",
        "Indicadores de gestión, trazabilidad, informes analíticos"
    )
    c5.associaciones = {"datos": 0.8, "hechos": 0.7}
    memoria.agregar(c5)

    return memoria

def aprendizaje(memoria):
    print("\n🧠 Simulación ACTR-Analogic - Aprendizaje ISO 9001:2015")

    opciones = [
        "1. Enfoque basado en procesos",
        "2. Mejora continua",
        "3. Enfoque al cliente",
        "4. Liderazgo",
        "5. Toma de decisiones basada en la evidencia"
    ]

    print("\n📚 Conceptos disponibles:")
    for o in opciones:
        print(f"   {o}")

    seleccion = input("\n➡️ Escribe el número del concepto que deseas aprender (1 a 5): ").strip()

    if seleccion == "1":
        termino = "Enfoque basado en procesos"
    elif seleccion == "2":
        termino = "Mejora continua"
    elif seleccion == "3":
        termino = "Enfoque al cliente"
    elif seleccion == "4":
        termino = "Liderazgo"
    elif seleccion == "5":
        termino = "Toma de decisiones basada en la evidencia"
    else:
        print("❌ Opción no válida.")
        return

    contexto = input("🔎 Palabras clave relacionadas (separadas por espacio): ").strip().split()

    if not contexto:
        print("⚠️ Debes ingresar al menos una palabra clave.")
        return

    pesos = [1.0 / len(contexto)] * len(contexto)

    chunk = memoria.buscar(termino, contexto, pesos, externo=True)

    if chunk:
        print(f"\n📘 Definición: {chunk.definicion}")
        print(f"\n🔁 Analogía aplicada: {chunk.analogia}")
        print(f"\n🌐 Fuente externa: {chunk.fuente_externa}")
        print(f"\n⏱️ Tiempo de recuperación: {round(chunk.tiempo_recuperacion(), 2)} segundos")
        print(f"🔥 Activación total: {round(chunk.activacion, 2)}")
    else:
        print("❌ No se pudo recuperar el concepto (activación insuficiente).")

# Ejecutar la simulación
memoria = crear_memoria_iso()
aprendizaje(memoria)

# Función para calcular el Resultado Cognitivo (RC)
def resultado_cognitivo(base_RC=0.6, usa_RA=True, usa_CSD=True):
    lambda_RA = 0.3 if usa_RA else 0.0
    lambda_CSD = 0.4 if usa_CSD else 0.0
    RC = base_RC + lambda_RA + lambda_CSD
    return round(RC, 2)

# Simulación de cálculo del resultado cognitivo
print("\n🧮 Cálculo del Resultado Cognitivo:")

# Preguntar si se usó razonamiento analógico
usa_RA = input("¿Se aplicó una analogía? (s/n): ").strip().lower() == "s"
# Preguntar si hubo apoyo externo (CSD)
usa_CSD = input("¿Hubo apoyo de una fuente externa o colaborativa? (s/n): ").strip().lower() == "s"

# Calcular resultado
rc_final = resultado_cognitivo(0.6, usa_RA, usa_CSD)
print(f"\n✅ Resultado Cognitivo estimado: {rc_final}")

import math

# Función Softmax para seleccionar acciones cognitivas
def softmax_seleccion(utilidades, theta=0.7):
    exps = [math.exp(u / theta) for u in utilidades]
    total = sum(exps)
    probabilidades = [round(e / total, 4) for e in exps]
    return probabilidades

# Acciones posibles (producciones cognitivas)
acciones = [
    "Explicar con analogía",
    "Buscar fuente externa",
    "Leer documento oficial",
    "Preguntar en foro colaborativo"
]

# Utilidades estimadas de cada acción (mayor = mejor)
utilidades = [0.9, 0.7, 0.5, 0.8]  # Puedes modificarlas

# Calcular probabilidades con softmax
probabilidades = softmax_seleccion(utilidades)

# Mostrar resultados
print("\n🎯 Probabilidades de seleccionar cada acción (Softmax):\n")
for i in range(len(acciones)):
    print(f"- {acciones[i]}: {probabilidades[i]*100:.1f}%")

# Cálculo de Interacción Cognitiva Distribuida
def calcular_ICD(grados_influencia, pesos_fuentes):
    ICD = sum(w * i for w, i in zip(pesos_fuentes, grados_influencia))
    return round(ICD, 2)

# Simulación de fuentes activas
fuentes = [
    "Profesor experto",
    "Simulación ISO digital",
    "Compañero de equipo",
    "IA educativa (como ChatGPT)"
]

# Nivel de implicación cognitiva (0.0 a 1.0)
influencias = [0.9, 0.7, 0.6, 0.8]

# Peso asignado a cada fuente (confiabilidad, experiencia, acceso)
pesos = [0.9, 0.7, 0.5, 0.8]

# Calcular ICD
icd = calcular_ICD(influencias, pesos)

# Mostrar resultados
print("\n🔗 Interacción Cognitiva Distribuida (ICD):")
for i in range(len(fuentes)):
    print(f"- {fuentes[i]}: I={influencias[i]}  | W={pesos[i]}")
print(f"\n✅ Nivel total de interacción cognitiva distribuida: {icd}")

pip install streamlit

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile actr_analogic_app.py
# import streamlit as st
# import math
# 
# # Configurar la página
# st.set_page_config(
#     page_title="Simulación Cognitiva ACTR-Analogic",
#     layout="centered",
#     initial_sidebar_state="expanded"
# )
# 
# # Título de la app
# st.title("🧠 Simulación Cognitiva ACTR-Analogic")
# st.subheader("Norma ISO 9001:2015 – Aprendizaje Basado en Cognición Distribuida y Razonamiento Analógico")
# 
# # Descripción introductoria
# st.markdown("""
# Esta aplicación simula cómo una persona aprende conceptos clave de la norma **ISO 9001:2015**
# utilizando analogías y activación cognitiva distribuida.
# Está basada en la arquitectura **ACTR-Analogic**, un modelo que amplía ACT-R
# para integrar herramientas digitales, interacciones sociales y analogías como mecanismos de aprendizaje híbrido.
# 
# ---
# 
# **¿Qué podrás hacer aquí?**
# 
# - 📘 Aprender un concepto ISO con analogías.
# - 📈 Ver cómo se activa cognitivamente esa información.
# - 🔁 Simular el resultado cognitivo.
# - 🔗 Explorar el impacto de la interacción distribuida.
# 
# Desarrollado con ❤️ en Streamlit.
# """)
# 
# # -------------------------------------
# # SESIÓN 2: Módulo de Aprendizaje ACTR-Analogic
# # -------------------------------------
# 
# st.markdown("---")
# st.header("📘 Aprendizaje de conceptos ISO 9001:2015")
# 
# # Diccionario de conceptos con analogía y fuente externa
# conceptos_iso = {
#     "Enfoque basado en procesos": {
#         "definicion": "Gestión de actividades como procesos interrelacionados que contribuyen al valor del cliente.",
#         "analogia": "Como una orquesta: cada instrumento (proceso) aporta a la sinfonía.",
#         "fuente": "Simulación empresarial, mapa de procesos"
#     },
#     "Mejora continua": {
#         "definicion": "Compromiso permanente con la mejora del desempeño global.",
#         "analogia": "Como escalar una montaña paso a paso.",
#         "fuente": "Estudio de caso, retroalimentación grupal"
#     },
#     "Enfoque al cliente": {
#         "definicion": "Satisfacer y superar las expectativas del cliente es el objetivo central.",
#         "analogia": "Como un restaurante que adapta sus recetas según las opiniones de los comensales.",
#         "fuente": "Encuestas de satisfacción, reseñas digitales"
#     },
#     "Liderazgo": {
#         "definicion": "Los líderes establecen dirección y fomentan una cultura de compromiso.",
#         "analogia": "Como el capitán de un barco que guía a su tripulación.",
#         "fuente": "Simuladores de liderazgo, entrevistas con directivos"
#     },
#     "Toma de decisiones basada en evidencia": {
#         "definicion": "Las decisiones eficaces se fundamentan en el análisis de datos y hechos.",
#         "analogia": "Como un médico que receta basado en exámenes clínicos, no suposiciones.",
#         "fuente": "Dashboards, indicadores de calidad"
#     }
# }
# 
# with st.form("form_aprendizaje"):
#     concepto = st.selectbox("Selecciona un concepto ISO:", list(conceptos_iso.keys()))
#     contexto = st.text_input("🔎 Palabras clave relacionadas (separadas por espacio)", "")
#     submitted = st.form_submit_button("🧠 Simular Aprendizaje")
# 
#     if submitted:
#         datos = conceptos_iso[concepto]
#         palabras = contexto.split()
#         activacion = 1.0 + 0.3 * len(palabras)
#         tiempo = round(0.5 * (2.7 ** (-activacion)), 2)
# 
#         st.success("✅ Concepto recuperado con éxito")
#         st.markdown(f"**📘 Definición:** {datos['definicion']}")
#         st.markdown(f"**🔁 Analogía sugerida:** _{datos['analogia']}_")
#         st.markdown(f"**🌐 Fuente externa sugerida:** {datos['fuente']}")
#         st.markdown(f"**🔥 Activación simulada:** `{round(activacion, 2)}`")
#         st.markdown(f"**⏱️ Tiempo estimado de recuperación:** `{tiempo} segundos`")
# 
#         st.text_area("✍️ Escribe tu propia analogía (opcional):")
#         st.multiselect("🌍 Herramientas/personas que te ayudaron a aprender:",
#                        ["ChatGPT", "Foros académicos", "Videos explicativos", "Compañeros", "Simuladores", "Docente"])
#

!streamlit run actr_analogic_app.py & npx localtunnel --port 8501